"""
Domain template generation system
Provides pre-built templates for creating new cognitive domains
"""

# Domain template - minimal cognitive domain
DOMAIN_TEMPLATE = '''"""
{domain_name_display} Domain
Auto-generated by BlackMamba CLI
"""

from typing import Dict, Any, Optional
from blackmamba.core.interfaces import DomainProcessor
from blackmamba.core.types import ProcessedInput, CognitiveResponse


class {domain_class_name}Domain(DomainProcessor):
    """
    {domain_name_display} cognitive domain processor.
    
    This domain handles: {description}
    """
    
    def __init__(self):
        """Initialize the domain"""
        super().__init__()
        # Add your initialization here
        self.knowledge_base = {{
            # Your domain-specific knowledge
        }}
    
    @property
    def domain_name(self) -> str:
        """Return the domain identifier"""
        return "{domain_name}"
    
    async def can_handle(
        self,
        input_data: ProcessedInput,
        context: Optional[Dict[str, Any]] = None
    ) -> bool:
        """
        Determine if this domain can handle the input.
        
        Args:
            input_data: The processed input
            context: Optional context information
            
        Returns:
            True if this domain can process the input
        """
        # Implement your logic to determine if this domain should handle the input
        # Example: check for specific keywords, event types, or patterns
        
        if input_data.input_type == "text":
            # Check if text contains domain-specific keywords
            keywords = ["keyword1", "keyword2"]  # Replace with your keywords
            return any(keyword in input_data.content.lower() for keyword in keywords)
        
        elif input_data.input_type == "event":
            # Check if event type matches
            event_type = input_data.metadata.get("event_type")
            return event_type in ["event_type_1", "event_type_2"]  # Replace with your event types
        
        return False
    
    async def analyze(
        self,
        input_data: ProcessedInput,
        context: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        Analyze the input and extract insights.
        
        Args:
            input_data: The processed input
            context: Optional context information
            
        Returns:
            Dictionary containing analysis results
        """
        analysis = {{
            "domain": self.domain_name,
            "input_type": input_data.input_type,
            "timestamp": input_data.timestamp,
        }}
        
        # Implement your analysis logic here
        # Example: extract features, classify, detect patterns, etc.
        
        if input_data.input_type == "text":
            # Analyze text
            analysis["text_length"] = len(input_data.content)
            analysis["insights"] = "Add your insights here"
        
        elif input_data.input_type == "event":
            # Analyze event
            analysis["event_type"] = input_data.metadata.get("event_type")
            analysis["insights"] = "Add your insights here"
        
        return analysis
    
    async def synthesize(
        self,
        input_data: ProcessedInput,
        context: Optional[Dict[str, Any]] = None,
        analysis: Optional[Dict[str, Any]] = None
    ) -> CognitiveResponse:
        """
        Generate a response based on analysis.
        
        Args:
            input_data: The processed input
            context: Optional context information
            analysis: Analysis results from analyze()
            
        Returns:
            CognitiveResponse with recommendations/insights
        """
        # Use analysis to generate response
        confidence = 0.8  # Calculate based on your logic
        
        # Generate response content
        response_content = f"Processed {{input_data.input_type}} in {{self.domain_name}} domain."
        
        # Add recommendations
        recommendations = [
            "Recommendation 1: Add your recommendations here",
            "Recommendation 2: Based on your analysis",
        ]
        
        return CognitiveResponse(
            content=response_content,
            confidence=confidence,
            metadata={{
                "domain": self.domain_name,
                "analysis": analysis,
                "recommendations": recommendations,
            }}
        )
'''

# Example usage template
EXAMPLE_TEMPLATE = '''"""
Example usage of {domain_name_display} domain
"""

import asyncio
from blackmamba.core.engine import CognitiveEngine
from blackmamba.core.input_processor import InputProcessor
from {domain_module} import {domain_class_name}Domain


async def main():
    """Demonstrate the {domain_name_display} domain"""
    # Initialize components
    processor = InputProcessor()
    engine = CognitiveEngine(input_processor=processor)
    
    # Register your domain
    domain = {domain_class_name}Domain()
    engine.register_domain_processor(domain)
    
    # Example 1: Process text
    print("Example 1: Text processing")
    input_data = await processor.process_text(
        "Your example text here with keyword1"
    )
    response = await engine.process(input_data)
    
    print(f"Response: {{response.content}}")
    print(f"Confidence: {{response.confidence}}")
    if response.metadata:
        print(f"Recommendations: {{response.metadata.get('recommendations')}}")
    
    # Example 2: Process event
    print("\\nExample 2: Event processing")
    input_data = await processor.process_event({{
        "event_type": "event_type_1",
        "data": {{
            "key": "value"
        }}
    }})
    response = await engine.process(input_data)
    
    print(f"Response: {{response.content}}")
    print(f"Confidence: {{response.confidence}}")


if __name__ == "__main__":
    asyncio.run(main())
'''

# Test template
TEST_TEMPLATE = '''"""
Tests for {domain_name_display} domain
"""

import pytest
from blackmamba.core.input_processor import InputProcessor
from {domain_module} import {domain_class_name}Domain


@pytest.fixture
def domain():
    """Create domain instance"""
    return {domain_class_name}Domain()


@pytest.fixture
def processor():
    """Create input processor"""
    return InputProcessor()


@pytest.mark.asyncio
async def test_domain_name(domain):
    """Test domain name property"""
    assert domain.domain_name == "{domain_name}"


@pytest.mark.asyncio
async def test_can_handle_text(domain, processor):
    """Test text handling detection"""
    input_data = await processor.process_text("test keyword1")
    can_handle = await domain.can_handle(input_data)
    assert isinstance(can_handle, bool)


@pytest.mark.asyncio
async def test_analyze(domain, processor):
    """Test analysis function"""
    input_data = await processor.process_text("test input")
    analysis = await domain.analyze(input_data)
    
    assert isinstance(analysis, dict)
    assert "domain" in analysis
    assert analysis["domain"] == "{domain_name}"


@pytest.mark.asyncio
async def test_synthesize(domain, processor):
    """Test synthesis function"""
    input_data = await processor.process_text("test input")
    analysis = await domain.analyze(input_data)
    response = await domain.synthesize(input_data, analysis=analysis)
    
    assert response.content is not None
    assert 0 <= response.confidence <= 1
    assert response.metadata is not None


@pytest.mark.asyncio
async def test_full_pipeline(domain, processor):
    """Test complete processing pipeline"""
    input_data = await processor.process_text("keyword1 test")
    
    can_handle = await domain.can_handle(input_data)
    if can_handle:
        analysis = await domain.analyze(input_data)
        response = await domain.synthesize(input_data, analysis=analysis)
        assert response is not None
'''

# README template
README_TEMPLATE = '''# {domain_name_display} Domain

Auto-generated cognitive domain for BlackMamba.

## Description

{description}

## Installation

This domain is part of your BlackMamba installation.

## Usage

```python
from blackmamba.core.engine import CognitiveEngine
from blackmamba.core.input_processor import InputProcessor
from blackmamba.domains.{domain_name} import {domain_class_name}Domain

# Initialize
processor = InputProcessor()
engine = CognitiveEngine(input_processor=processor)

# Register domain
engine.register_domain_processor({domain_class_name}Domain())

# Use it
input_data = await processor.process_text("your input")
response = await engine.process(input_data)
```

## Examples

See `examples/{domain_name}_example.py` for complete examples.

## Testing

```bash
pytest tests/unit/test_{domain_name}.py
```

## Customization

To customize this domain:

1. Edit `blackmamba/domains/{domain_name}.py`
2. Update the `can_handle()` method to detect relevant inputs
3. Implement your analysis logic in `analyze()`
4. Generate responses in `synthesize()`
5. Add tests in `tests/unit/test_{domain_name}.py`

## Architecture

This domain follows the BlackMamba cognitive architecture:

```
Input → can_handle() → analyze() → synthesize() → Response
```

## Contributing

Contributions are welcome! Please follow the BlackMamba contribution guidelines.

## License

MIT License - See LICENSE file for details.
'''
